plugin: aws_ec2
regions:
  - "us-east-1"
keyed_groups:
  - key: tags.Role
    prefix: splunk_single_site_idxr_cluster
filters:
  instance-state-name : running
compose:
  ansible_host: public_ip_address
  instance_id: id
  ansible_private_ip: private_ip_address
